### PR TITLE
allow enabling docker's remote API

### PR DESCRIPTION
**Pull request by AntonioMeireles**

### CODE REVIEW

**Comment by YungSang** [comment]
My boxes already have docker-tcp.socket and enabled them.

BTW, do you think these port forwardings are needed in general actually?
How do you handle these ports to access to Docker daemon from host?

**Comment by AntonioMeireles** [comment]
one just needs to have **DOCKER_HOST="tcp://${CoreOS_workerVM_ip}:xxxx"** populated and pointing to a running VM. [docker doesn't care if it is CoreOS or boot2docker :-) ]

**Comment by YungSang** [comment]
So you do `export DOCKER_HOST="xxxxx"` to access to each CoreOS node each time?
I don't think that is an easy way to use docker command in the host.
I do `vagrant ssh core-1` and then `docker xxx`, or just `vagrant ssh core-1 -c "docker xxx"`.

**Comment by AntonioMeireles** [comment]
matter of taste i suppose. if you 're in a hurry you load only one VM (2 right now, counting with the etcd one) and you get a mostly boot2docker drop in. the main point in favor of setting DOCKER_HOST is that if you are working in windows/multiple places (some with _native_ docker) cli invocation gets exactly the same...

**Comment by YungSang** [comment]
I don't have intent for this to use a single vm like boot2docker.
It is to create a cluster. That's why we have an etcd discovery and cloud-configs to do that.
I don't like it have many usages in one configuration.

**Pull request closed without merging**
